### ISSUE TITLE
Service of type LB gets private and public external-ip

### ISSUE THREAD

**Issue by plicon** [hetznercloud/hcloud-cloud-controller-manager#118]
I've setup the cloud controller and configured it to automagically create a hetzner LB, so far so good. The load balancer is connected to the same LAN as the k8s worker nodes. 
I setup a service using the following definition, which nicely also creates the LB. 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/use-private-ip: "true"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

When i describe the created the service it shows both the LB's private and PUBLIC ip-adress as shown below: 
```yaml
Name:                     nginx
Namespace:                traefik
Labels:                   <none>
Annotations:    
                          load-balancer.hetzner.cloud/location: hel1
                          load-balancer.hetzner.cloud/use-private-ip: true                         
                          field.cattle.io/publicEndpoints: [{"addresses":["10.0.10.4","95.217.175.215"],"port":80,"protocol":"TCP","serviceName":"traefik:nginx","allNodes":false}]
Selector:                 app=nginx
Type:                     LoadBalancer
IP:                       10.43.240.86
LoadBalancer Ingress:     95.217.175.215, 10.0.10.4
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  30257/TCP
Endpoints:                10.244.2.23:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

The issue I then ran into is that using [external-dns](https://github.com/kubernetes-sigs/external-dns) with cloudflare for both ip-adresses a dns a-record is created. 

I would expect the service to only have the public ip-adress as loadbalacner-ingress.
