### ISSUE TITLE
Updated annotations on load balancer are not always respected

### ISSUE THREAD

**Issue by codello** [hetznercloud/hcloud-cloud-controller-manager#120]
I am currently playing around with Hetzner's load balancers in kubernetes. When changing certain annotations on a service of `type: LoadBalancer` these do not seem to be applied to the actual load balancer. I have experienced this with the following annotations. Changing any other annotations seem to work fine.
- `load-balancer.hetzner.cloud/location`: Changing the location of a load balancer does not seem to have any effect.
- `load-balancer.hetzner.cloud/network-zone`: Changing the network zone of a load balancer (either from another `network-zone` or from a different `location`) does not seem to have any effect.
- `load-balancer.hetzner.cloud/disable-public-network`: Changing this annotation does not seem to have any effect.
- `load-balancer.hetzner.cloud/name`: Changing the name of a load balancer will create a new load balancer (this is correct as I don't think renaming a load balancer is possible). However the old load balancer is **not deleted** and has to be removed manually.

The logs of the `hlcloud-cloud-controller-manager` pod do not show any errors, only
```
I1116 19:42:16.784156       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=80 loadBalancerID=136770
I1116 19:42:17.763876       1 load_balancers.go:117] "reload HC Load Balancer" op="hcloud/loadBalancers.EnsureLoadBalancer" loadBalancerID=136770
I1116 19:42:18.078668       1 event.go:278] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"lb-service", UID:"d0e70749-64f5-4782-a903-ae88a0d59c8d", APIVersion:"v1", ResourceVersion:"8215", FieldPath:""}): type: 'Normal' reason: 'EnsuredLoadBalancer' Ensured load balancer
```

I would expect the following:
- Enabling/disabling the public network is possible by changing the annotation on the service.
- Changing the `name`, `location` or `network-zone` of a load balancer creates a new instance with the respective name/location and deletes the old instance.

Related: If a load balancer with a specified `load-balancer.hetzner.cloud/name` already exists it will be modified. I would expect the cloud controller manager to raise an error as to not accidentally modify an existing load balancer. However this should probably be discussed in its own issue.

---

My environment:
- 3 node cluster (3x CPX11), 1 master, 2 workers. The master sits behind its own load balancer. All located in `nbg1`.
- Kubernetes and `kubectl` version v1.19.4
- The cluster is bootstrapped via `kubeadm` on CentOS 8, as described [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/).
- `hcloud-cloud-controller-manager` v1.8.1, deployed via Matthias Lohr's [helm chart](https://gitlab.com/MatthiasLohr/hcloud-cloud-controller-manager-helm-chart). I am using a private node network, the ccm is configured to use the private network.
- I am using calico as CNI plugin, however the issue also occurs when no CNI plugin is installed.

For testing I used the following service manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  annotations:
    load-balancer.hetzner.cloud/location: ngb1  # Change this
#     load-balancer.hetzner.cloud/network-zone: nbg-dc3  # Change this
    load-balancer.hetzner.cloud/name: test-lb  # Change this
    load-balancer.hetzner.cloud/disable-public-network: "false"  # Change this
spec:
  type: LoadBalancer
  selector:
  ports:
    - name: http
      port: 80
```
