### ISSUE TITLE
cant get it running ccm for k3s 1.18 

### ISSUE THREAD

**Issue by lachnerd** [hetznercloud/hcloud-cloud-controller-manager#162]
Im getting a the following error if i try to get a Loadbalancer on k3s v1.18.10+k3s2 with hetzner:

"Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set"

- I added --cloud-provider=external
- i didnt execute the flannel patch cause there are some errors
- i created a secret
- and i deployed the yaml for network & ccm according to the matrix

csi driver btw. is working fine.

Any clues ?

**Comment by LKaemmerling** [comment]
Looks like you created a service type loadbalancer somewhere which is missing the written annotations. You need to set at least one annotation on the Service, otherwise the CCM does not know where it should create the loadbalancer

**Comment by lachnerd** [comment]
thx, good hint i will try that

**Comment by lachnerd** [comment]
ok, thx got it working now.

Also [this](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/load_balancers.md) helped me a lot - i simply didnt understand that i have to set additional Environment Variables or Annotations.

I also only got the secret for csi set with only the hcloud_token and missed that there is a slighlty different named secret needed with token and network-id.

Next problem was that i got a typo when setting "--cloud-provider=external" (you get a hint for that in the logs of the cloudmanager pod - something like "missing hcloud:// at url")

Maybe this helps others with similar problems.

**Comment by lachnerd** [comment]
ok, i thougt i got it working but it doesn't.

I am able create a Hetzner Load Balancer with a Loadbalancer Service deployed to k3s but it's useless:
- i don't get any external IP Adress
- error events are thrown

I tested with some simple app:
```
kind: Service
apiVersion: v1
metadata:
  name: whoami-application
  annotations:
    #https://pkg.go.dev/github.com/hetznercloud/hcloud-cloud-controller-manager/internal/annotation
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/network-zone: nbg1
  labels:
    app: whoami-application
    workshop: workshop
spec:
  type: LoadBalancer  
  ports:
    -
      name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: whoami-application
```

- I tried different k3s versions (1.18 to 1.19)
- cloud-provider=external
  - i set the "--cloud-provider=external" flag by setting "export KUBELET_EXTRA_ARGS=--cloud-provider=external"
  - i set it also with '--kubelet-arg="cloud-provider=external"'
 - i even set --kubelet-arg='provider-id=hcloud://<HOSTNAME>

all i get is:
```
hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: hcops/providerIDToServerID: missing prefix hcloud://
```
or
```
hcops/LoadBalancerOps.ReconcileHCLBTargets: hcops/providerIDToServerID: missing prefix hcloud://: k3s://
```
