### ISSUE TITLE
Kubernetes load balancer on Hetzner Cloud not working

### ISSUE THREAD

**Issue by hershkoy** [hetznercloud/hcloud-cloud-controller-manager#173]
I am trying to follow the instructions on [Load Balancers](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/load_balancers.md) documentation

I have a kubernetes cluster running on hetzner (using calico with hcloud-cloud-controller-manager/v1.6.1), and I am trying to expose it so I can access it from outside.

I added a load balancer to the project, and I installed it as a service:

```
apiVersion: v1
kind: Service
metadata:
  name: magento-lb
  annotations:
   load-balancer.hetzner.cloud/location: nbg1
spec:
  selector:
    app: magento-lb
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
    - name: "https"
      port: 443
      targetPort: 8443
  type: LoadBalancer
```

When I am inside the worker node, I can connect to my nginx pod that is listening on port 8080. I have a ping to the load balancer ip, but when curl or browser doesn't work (getting `curl: (52) Empty reply from server`).

```
$ kubectl get svc:
NAME          TYPE           CLUSTER-IP       EXTERNAL-IP               PORT(S)                      AGE
db            ClusterIP      10.102.126.120   <none>                    3306/TCP                     28m
kubernetes    ClusterIP      10.96.0.1        <none>                    443/TCP                      16d
magento-lb    LoadBalancer   10.105.100.43    10.0.2.1,123.123.123.12   80:30255/TCP,443:30358/TCP   27m
magento-php   ClusterIP      10.108.46.78     <none>                    9000/TCP                     28m
magento-web   ClusterIP      10.97.160.3      <none>                    8080/TCP,8443/TCP            28m
```

This is from inside the worker node, a curl to the ip of the nginx pod:

```
[root@worker-0 ~]# curl -v http://10.97.160.3:8080/health_check.php
* About to connect() to 10.97.160.3 port 8080 (#0)
*   Trying 10.97.160.3...
* Connected to 10.97.160.3 (10.97.160.3) port 8080 (#0)
> GET /health_check.php HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.97.160.3:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.17.10
< Date: Tue, 23 Mar 2021 21:17:29 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: PHP/7.2.34
< 
* Connection #0 to host 10.97.160.3 left intact
```

On on Hetzner dashboard the load balancer appears as unhealthy. In addition, I don't understand the target port of the load balancer, it was assigned wrong port numbers by the controller. For http it was 30255. The nginx is listening on 8080. So I changed it in the Hetzner dashboard. But it didn't work with 30255 and it doesn't work with 8080

How to connect the cluster to the load balancer?

![image](https://user-images.githubusercontent.com/13259380/112279009-16c12980-8c8c-11eb-83e1-94fa7a05381f.png)

**Comment by hershkoy** [comment]
I managed to get it working using ingress-nginx

**Comment by laukaichung** [comment]
Hello,

I try to use your [magento2 repo](https://github.com/hershkoy/magento2-on-kubernetes/tree/7dc2e4d409b863ac88619e3067ec8f80638a2711/deploy/bases/app) as a reference to use LB as an ingress nginx

Install Ingress Nginx via helm with these parameters:

````
controller:
  config:
    use-proxy-protocol: "true"
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: nginx-controller-new
      load-balancer.hetzner.cloud/location: hel1
      load-balancer.hetzner.cloud/algorithm-type: least_connections
      load-balancer.hetzner.cloud/uses-proxyprotocol: true
      load-balancer.hetzner.cloud/http-redirect-https: 'false'
```` 

Deployments:
````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  replicas: 3
  template:
    metadata:
      labels:
        app: echo1
    spec:
      containers:
        - name: echo1
          image: hashicorp/http-echo
          args:
            - "-text=echo1 deployment"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5678

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: echo-service
      port:
        name: http
````
The 32740 and 32537 are ports to ingress controller pods but the health checks all fail
![Image Info](https://i.ibb.co/zHRMWQm/Screenshot-2021-05-30-11-01-49.png)

What I don't understand is how Ingress Nginx connects to echo service? The Ingress kind doesn't work.
