### ISSUE TITLE
Disable load balancer targets for specific nodes

### ISSUE THREAD

**Issue by sergeyshevch** [hetznercloud/hcloud-cloud-controller-manager#182]
Can we add some labels to remove some nodes from load balancer targets?

Or maybe it can be great feature to enable load balancer targets only for certain nodes

**Comment by Shadowghost** [comment]
You can exclude nodes from load-balancing by enabling the FeatureGate `ServiceNodeExclusion` for the CCM:
```bash
kubectl edit -n kube-system deployments.apps hcloud-cloud-controller-manager
```
Add the following line:
```yaml
...
spec:
...
  template:
...
    spec:
      containers:
      - command:
...
        - --feature-gates=ServiceNodeExclusion=true
...
```
Edit the nodes you want to exclude and add the exclusion label:
```bash
kubectl edit nodes <node>
```
```yaml
...
metadata:
...
  labels:
...
    node.kubernetes.io/exclude-from-external-load-balancers: "true"
...
```

The CCM pod(s) should automatically be recreated, recognize the new label and configure your LB accordingly. You need to do the changes to the CCM again after you upgrade it.
