### ISSUE TITLE
LoadBalancer created, green, but 503 Error on Request

### ISSUE THREAD

**Issue by blafasel42** [hetznercloud/hcloud-cloud-controller-manager#185]
I  managed to install the manager and it now auto-creates load-balancers. My service config for load-balancer use (rancher-cluster) looks like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/name: test
    load-balancer.hetzner.cloud/health-check-port: "10254"
    load-balancer.hetzner.cloud/health-check-protocol: "http"
    load-balancer.hetzner.cloud/health-check-http-path: "/healthz"
    load-balancer.hetzner.cloud/protocol: "http"
  creationTimestamp: null
  labels:
    service: app
  name: app
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: 8000
  selector:
    service: app
status:
  loadBalancer: {}
```

In the UI i see all worker nodes green (health check works), but the controller node is also added as a target and it is red. I don't understand why not only worker nodes are added, but this should not be a problem though.

However, when i access the LB from outside (GET request to public IP of the LB), i always get "503 no server available". 

The "service" definition of the LB is like "http:80 -> 30183"
