### ISSUE TITLE
Disabling IPv6 for loadbalancers

### ISSUE THREAD

**Issue by deyaeddin** [hetznercloud/hcloud-cloud-controller-manager#191]
Hello,
Is there an option "annotation/flag" to disable IPv6 Support ? 

I have upgraded CCM to v1.9.1 but the external-dns erroring to : the target A is not a valid record. As there is an open issue with external-dns regarding IPv6 support  kubernetes-sigs/external-dns/issues/2044 

I understand the feature was re-enabled #137 , but the ingress-nginx-controller is always publishing both IPv4 and IPv6 even with ConfigMap -> disable-ipv6-dns: "true" 

The only workaround I found is to go back to v1.8.1 where IPv6 is completely not supported.

**Comment by janosmiko** [comment]
Hi @fhofherr ,

I'm not sure if this fix actually solved the issue.

I'm using the latest version of CCM and I can still see these error messages in the external-dns POD logs:
```
me="2021-06-08T13:46:41Z" level=info msg="Desired change: CREATE domain.example.com A [Id: /hostedzone/XYZ123]"
time="2021-06-08T13:46:41Z" level=info msg="Desired change: CREATE domain.example.com TXT [Id: /hostedzone/XYZ123]"
time="2021-06-08T13:46:41Z" level=error msg="Failure in zone example.com. [Id: /hostedzone/XYZ123]"
time="2021-06-08T13:46:41Z" level=error msg="InvalidChangeBatch: [Invalid Resource Record: 'FATAL problem: ARRDATAIllegalIPv4Address (Value is not a valid IPv4 address) encountered with '2a01:4f8:1c1d:11c::1'']\n\tstatus code: 400, request id: 2c1833a2-7246-429e-b8eb-32cf712d206f"
time="2021-06-08T13:46:41Z" level=error msg="failed to submit all changes for the following zones: [/hostedzone/XYZ123]"
```

I'm using these kustomizations/annotations on the ingress controller service:
```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  annotations:
    externalTrafficPolicy: Local
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
```

I also tried it with `true` without the quotes, that didn't help either.


As @deyaeddin suggested I also rolled back to 1.8.1 and now external-dns works like a charm:
```
time="2021-06-08T13:54:45Z" level=info msg="2 record(s) in zone itg.cloud. [Id: /hostedzone/XYZ123] were successfully updated"
```
