### ISSUE TITLE
Seperate releases for each supported Kubernetes version

### ISSUE THREAD

**Issue by Illianthe** [hetznercloud/hcloud-cloud-controller-manager#197]
Hi! For context, I was looking into why my control plane nodes weren't being added to a load balancer. From a [previous issue](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/101), removing the master role does fix this; unfortunately this seems a bit fragile as certain distributions like k3s eventually adds it back.

After digging into it a bit, it looks like recent versions of k8s introduced several feature flags (`LegacyNodeRoleBehavior`, `ServiceNodeExclusion`, and `NodeDisruptionExclusion`) to change this behaviour. Passing `LegacyNodeRoleBehavior=false` to the CCM also allows control plane nodes to be added to the LB. E.g.

```
...
      containers:
        - image: hetznercloud/hcloud-cloud-controller-manager:v1.10.0
          name: hcloud-cloud-controller-manager
          command:
            - "/bin/hcloud-cloud-controller-manager"
            - "--cloud-provider=hcloud"
            - "--leader-elect=false"
            - "--allow-untagged-cloud"
            - "--allocate-node-cidrs=true"
            - "--cluster-cidr=10.244.0.0/16"
            - "--feature-gates=LegacyNodeRoleBehavior=false"
...
```

This surprised me at first as my cluster is currently running v1.21 where `LegacyNodeRoleBehaviour` is already locked to false (and is being removed in v1.22), but then I realized that the CCM is using packages [based on v1.18.8](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/b54847b9163a3fc39dd902ab2f5f0494003b7230/go.mod#L35).

Would it make sense to have separate releases for each of the three supported k8s versions with updated dependencies, similar to what k3s does (e.g. v1.21.0+ccm1)? Alternatively, it might be worth documenting the above behaviour (at least until the cloud-provider package is bumped to >= 0.21).
