### ISSUE TITLE
How to create kubernetes cluster with LoadBalancer that uses HTTP protocol?

### ISSUE THREAD

**Issue by hershkoy** [hetznercloud/hcloud-cloud-controller-manager#198]
I suspect that the LB in my application is causing connection issues (I am getting timeout on a specific route). Reading on the internet, I see several suggestions that the issue is because of LB. 

The protocol of the load balancer in my cluster is 'TCP' (tcp on port 80). 
Is there a way to change it the LB protocol to 'http' (It is possible on the cloud dashboard, but can it be done from the yaml)?

This is the yaml:
https://github.com/hershkoy/magento2-on-kubernetes/blob/7dc2e4d409b863ac88619e3067ec8f80638a2711/deploy/bases/app/ingress/ingress-nginx.yaml#L265

![image](https://user-images.githubusercontent.com/13259380/118290771-7941e380-b4df-11eb-9614-0e87ebed561c.png)

**Comment by LKaemmerling** [comment]
Hey @hershkoy,

you can specify the protocol via the annotation `load-balancer.hetzner.cloud/protocol`. 

https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/internal/annotation/load_balancer.go#L54

**Comment by mstimvol** [comment]
I'm facing exactly the same problem at the moment. Using the `load-balancer.hetzner.cloud/protocol` fixes the problem for on of the ports. In my case I've a nginx ingress controller (https://github.com/nginxinc/kubernetes-ingress) and when I set `load-balancer.hetzner.cloud/protocol: http`, both ports (80 and 443) are created as http ports, although 443 should use the https protocol.
I already created a feature request for the nginx ingress controller but I'm not sure if there's another option here...

**Comment by chwzr** [comment]
Facing the same issue here. 

Adding the Annotation `load-balancer.hetzner.cloud/protocol` will affect all ports of an Service Definition.
I think Annotations are the wrong "tool" here. Maybe hetzner-cloud-controller-manager should parse the protocol of every port from the service definiton instead.

Looking at the standard ingress-nginx service description here:
```
...
spec:
  clusterIP: 10.43.102.130
  clusterIPs:
  - 10.43.102.130
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 30774
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 30987
    port: 443
    protocol: TCP
    targetPort: https
...
```

`spec.ports.appProtocol` seems the right property on services to me to parse protocol correctly. 

This will enable independent protocol settings on every Load-Balancer Service allowing to serve http and https traffic.
