### ISSUE TITLE
The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by laukaichung** [hetznercloud/hcloud-cloud-controller-manager#210]
Ingress Nginx custom settings

````
controller:
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: server-lb
      load-balancer.hetzner.cloud/location: hel1
      load-balancer.hetzner.cloud/algorithm-type: least_connections
      load-balancer.hetzner.cloud/hostname: www.example.com
      load-balancer.hetzner.cloud/protocol: https
      load-balancer.hetzner.cloud/http-certificates: server-cert
````

````
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
spec:
  selector:
    app.kubernetes.io/name: web
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 3000
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: web
                port:
                  number: 443
            pathType: Prefix
            path: /
      host: www.example.com
````
This is a Hetzner load balancer created by Ingress Nginx:

![1](https://i.ibb.co/JKnZgKg/1.png)

Ingress nginx controller service ports:

````
NAME                       TYPE           CLUSTER-IP   EXTERNAL-IP         PORT(S)                      AGE
ingress-nginx-controller   LoadBalancer   <CLUSTER-IP>   www.example.com   80:31060/TCP,443:32461/TCP   24m
````

However, when I access https://www.example.com, it gives me `400 Bad Request` -

**The plain HTTP request was sent to HTTPS port**

The only way to make the web accessible is manually changing the https:443 destination port to 31060 in Hetzner panel, like this:

![2](https://i.ibb.co/qgKBzc7/2.png)

Is there a misconfiguration in ingress that throws the `The plain HTTP request was sent to HTTPS port` error?

**Comment by laukaichung** [comment]
Got a solution in https://github.com/tibordp/terraform-hcloud-dualstack-k8s/issues/14#issuecomment-859615416

If your domain is managed by Cloudflare and you are using staging issuer, make sure you have set the encryption mode to “Full” and not to “Full (Strict)”  in the Cloudflare SSL panel. Otherwise it would throw `526` Invalid SSL cert error.

````
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: xxx@email.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class:  nginx
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: web
                port:
                  number: 3000
            pathType: Prefix
            path: /
      host: www.site.com
  tls:
    - hosts:
        - www.site.com
      secretName: some-secret
````
