### ISSUE TITLE
Cannot create route hcloud/CreateRoute: invalid gateway (invalid_input)

### ISSUE THREAD

**Issue by brpaz** [hetznercloud/hcloud-cloud-controller-manager#214]
Hello. I am trying to create a k3s cluster with CIllium 1,9 as CNI and using the Hetzner network support. I followed the instructions on the [Deployment With Networks guide](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/deploy_with_networks.md), but I cannot get network to work on my cluster.

I checked the logs and found this:

```
E0624 14:15:29.558886 1 route_controller.go:217] Could not create route 11c22a0d-eccf-4c7e-ad84-5db85ba768fa 10.244.0.0/24 for node k3s-master: hcloud/CreateRoute: invalid gateway (invalid_input)
```

So, It´s giving an error when creating the routes.

My network configuration is like follows:

* Network ip range: - 10.0.0.0/8
* Network subnet  ip range -  10.244.0.0/16

And then on My Colliium config:

```yaml
  tunnel: disabled
  masquerade: "true"
  cluster-pool-ipv4-cidr: "10.244.0.0/16"
  cluster-pool-ipv4-mask-size: "16"
  enable-endpoint-routes: "true"
  native-routing-cidr: "10.0.0.0/8"
```

What I am missing here?

**Comment by LKaemmerling** [comment]
Hey @brpaz,

are your nodes already connected to the network? As a hint, we use the following cilium config within our tests: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/e2etests/templates/cilium.yml

**Comment by vaisov** [comment]
I tried various settings for Cilium, but I still get the same error. Last config I've tried:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  version: "v1.10.3"
  valuesContent: |-
    tunnel: disabled
    nativeRoutingCIDR: "10.0.0.0/8"
    enable-endpoint-routes: "true"
    kube-proxy-replacement: "probe"
    enable-external-ips: "false"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    l7Proxy: false
    encryption:
      enabled: true
      type: wireguard
```
