### ISSUE TITLE
Loadbalancer on "master" is "red"

### ISSUE THREAD

**Issue by exocode** [hetznercloud/hcloud-cloud-controller-manager#216]
Hi there, 

- I deployed a three node k8s cluster (`1 x master`, `2 x worker`), 
- the cluster has `cloud_provider.name=external`
- I have 1 `Loadbalancer`
- And 1 `Network`
- I `apply` the `current CMM with Network` https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml

I then deploy a Workload and a Loadbalancer 👍 

```yaml

---
apiVersion: "v1"
kind: Service
metadata:
  name: "nginx-hello-world"
  labels:
    app: "hello-world"
  annotations:
    load-balancer.hetzner.cloud/name: "lb-staging"
    load-balancer.hetzner.cloud/health-check-port: "10254" #You can find it in the ingress-nginx manifest.
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: "hello-world"
  type: LoadBalancer
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-hello-world"
  labels:
    app: "hello-world"
spec:
  selector:
    matchLabels:
      app: "hello-world"
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: "hello-world"
    spec:
      containers:
        - image: "nginx"
          name: "nginx-hello-world"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              name: "http
```

Everything fine so far: the loadbalancer balances the requests to the two worker nodes and is reachable through its public IP. 

<img width="350" alt="Bildschirmfoto 2021-07-09 um 01 09 10" src="https://user-images.githubusercontent.com/1597621/125003781-4425bd80-e058-11eb-8b3e-c93c0447da73.png">

<img width="564" alt="Bildschirmfoto 2021-07-09 um 01 09 03" src="https://user-images.githubusercontent.com/1597621/125003806-54d63380-e058-11eb-8e19-b751f3308570.png">

As you can see the "Master" is "not healthy".

And the taints...
```
# taints
node-role.kubernetes.io/controlplane=true:NoSchedule 
node-role.kubernetes.io/etcd=true:NoExecute

# labels
role=master
topology.kubernetes.io/region=fsn1
topology.kubernetes.io/zone=fsn1-dc14
```

...seems normal for me: the controlpane should not be loadbalanced. 

**Do I have to simply "remove" the Master node from the loadbalancers target list in the Hetzner Dashboard? or is there "cleaner" way to get everything "green"?**

Thank you in advance
