### ISSUE TITLE
Can't get SSL running

### ISSUE THREAD

**Issue by exocode** [hetznercloud/hcloud-cloud-controller-manager#221]
Hi there, 

say first, that this is not a bug. It's more a question to understand
**I am struggling to get "SSL" properly up and running.** 

In the days before Hetzners LoadBalancer, I did LB with two machines running in front of my workloads and securing my cluster with `cert-manager`, which was quite easy. 

But now everything seems a bit changed. I use Rancher to spin up my cluster. 
Before I click "create cluster" I select `External (Out-of-tree) (which is "KUBELET_EXTRA_ARGS=--cloud-provider=external")` and add these lines into the yaml: 
```yaml
rancher_kubernetes_engine_config:
  addons: |-
    ---
    kind: Secret
    apiVersion: v1
    metadata:
      name: hcloud
      namespace: kube-system
    stringData:
      network: "network-1-development"
      token: MY_TOKEN_HERE
  addons_include:
    - https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml
```
The cluster spins up and also creates a nginx-ingress-controller by itself (because I kept `Nginx Ingress = enabled`) and creates a health check port at 10254.

My domain of course points on my "lb-development" loadbalancer.

Then I create a Deployment and a Service with exactly these parameters:

```yaml
---
apiVersion: "v1"
kind: Service
metadata:
  name: "nginx-hello-world"
  labels:
    app: "hello-world"
  annotations:
    load-balancer.hetzner.cloud/name: "lb-development"
    load-balancer.hetzner.cloud/health-check-port: "10254" #You can find it in the ingress-nginx manifest.
spec:
  type: LoadBalancer
  selector:
    app: "hello-world"
  ports:
    - name: "http"
      port: 80
      targetPort: 80
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-hello-world"
  labels:
    app: "hello-world"
spec:
  selector:
    matchLabels:
      app: "hello-world"
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: "hello-world"
    spec:
      containers:
        - image: "rancher/hello-world"
          name: "nginx-hello-world"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              name: "http"
```

Everything is fine. The loadbalancer connects the servers automagically, and does it's job (loadbalancing my workloads) which makes me quite happy.

**Now the big question:

What do I have to change to map SSL/TLS to my workloads?**

I have a working certificate in my Hetzner Console.

- Do I have to delete the nginx-ingress-controller or change it in some way?
- **Where to put which ports? and hostnames?**
- **Which annotations do I have to use on my LoadBalancer service?**

I struggled the whole weekend, so my happyness factors is already quite low.
I am quite sure, that I missed somewhere only some tiny steps. 

**Any help would be appreciated.**

Thank you in advance

PS: These are the tutorials I followed mostly: 
https://jmrobles.medium.com/how-to-create-a-kubernetes-cluster-with-rancher-on-hetzner-3b2f7f0c037a
https://jmrobles.medium.com/how-to-setup-hetzner-load-balancer-on-a-kubernetes-cluster-2ce79ca4a27b

**Comment by exocode** [comment]
Finally I got it working:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world
  labels:
    app: hello-world
  annotations:
    load-balancer.hetzner.cloud/hostname: my.domain.com
    load-balancer.hetzner.cloud/http-certificates: ID_OF_CERTIFICATE
    load-balancer.hetzner.cloud/name: NAME_OF_LOADBALANCER
    load-balancer.hetzner.cloud/protocol: https

spec: 
  ports:
  - name: https
    nodePort: 32725
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  type: LoadBalancer

```

**Comment by exocode** [comment]
not completly: 
health check is not working anymore when I use `https`
```
I0713 00:54:18.395570      
1 event.go:278] Event(v1.ObjectReference{Kind:"Service", 
Namespace:"default", Name:"nginx-hello-world", UID:"3ee9d771-671d-4816-a18a-76529693516c", APIVersion:"v1", ResourceVersion:"230061", FieldPath:""}): 
type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer:
failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer:
hcops/LoadBalancerOps.ReconcileHCLBServices: invalid input in field 'health_check' (invalid_input)
```

These are my annotations
```
    load-balancer.hetzner.cloud/health-check-interval: 5s
    load-balancer.hetzner.cloud/health-check-port: "10254"
    load-balancer.hetzner.cloud/health-check-protocol: https
    load-balancer.hetzner.cloud/hostname: dev1.vonhier.at
    load-balancer.hetzner.cloud/http-certificates: managed-certificate-1-wildcard-vonhier
    load-balancer.hetzner.cloud/name: lb-development
    load-balancer.hetzner.cloud/protocol: https

```

**Comment by LKaemmerling** [comment]
> not completly:
> health check is not working anymore when I use `https`
> 
> ```
> I0713 00:54:18.395570      
> 1 event.go:278] Event(v1.ObjectReference{Kind:"Service", 
> Namespace:"default", Name:"nginx-hello-world", UID:"3ee9d771-671d-4816-a18a-76529693516c", APIVersion:"v1", ResourceVersion:"230061", FieldPath:""}): 
> type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer:
> failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer:
> hcops/LoadBalancerOps.ReconcileHCLBServices: invalid input in field 'health_check' (invalid_input)
> ```
> 
> These are my annotations
> 
> ```
>     load-balancer.hetzner.cloud/health-check-port: "10254"
>     load-balancer.hetzner.cloud/health-check-protocol: https
>     load-balancer.hetzner.cloud/hostname: dev1.vonhier.at
>     load-balancer.hetzner.cloud/http-certificates: managed-certificate-1-wildcard-vonhier
>     load-balancer.hetzner.cloud/name: lb-development
>     load-balancer.hetzner.cloud/protocol: https
> ```

Hey @exocode,

the Health Checks only allow protocol `tcp` and `http` : https://docs.hetzner.cloud/#load-balancer-actions-add-service

**Comment by exocode** [comment]
Sorry for reopening this issue. My problem is not solved,
I struggle now for days, with that task, so maybe you guys can help me out, I guess, it's only a tiny piece of setting/annotation:

From the working http examples above, I thought I can simpy apply the settings to an `Ingress`, but the loadbalancing process only works when I use a `kind: Service` with `type: "LoadBalancer"`, **but not with `kind: Ingress`** !

The reason I ask for an example configuration is, because my workloads must be placed on the same domain (called fanout): 
- my `app` is at the root path `/` and
- my `api` is at `/api`. 

As far as I know, this is only possible with an Ingress.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # I already tried to put here these annotations:
    # load-balancer.hetzner.cloud/hostname: my.domain.com
    # load-balancer.hetzner.cloud/http-certificates: managed-certificate-1-wildcard
    # load-balancer.hetzner.cloud/name: lb-development
    # load-balancer.hetzner.cloud/protocol: https
  name: my-ingress
  namespace: default
spec:
  rules:
  - host: my.domain.com
    http:
      paths:
      - backend:
          serviceName: my-api-service
          servicePort: 3000
        path: /api
        pathType: Prefix
      - backend:
          serviceName: my-app
          servicePort: 80
        path: /
        pathType: Prefix
```

My nginx-Ingress annotations are:
(nginx is running as `type: "LoadBalancer"`)

```yaml
controller: 
    service: 
      annotations: 
        load-balancer.hetzner.cloud/hostname: my.domain.com
        load-balancer.hetzner.cloud/name: lb-development
        load-balancer.hetzner.cloud/protocol: https
        load-balancer.hetzner.cloud/http-certificates: managed-certificate-1-wildcard

```

If you need more informations, please let me know.
The logs are "silent", so no errors....
