### ISSUE TITLE
LoadBalancer with letsEncrypt Certificate?

### ISSUE THREAD

**Issue by blafasel42** [hetznercloud/hcloud-cloud-controller-manager#223]
Hi,
i have seen that Loadbalancers at Hetzner now support letsEncrypt certs.
I tried the following config:

```yaml
  annotations:
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/name: ndx
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/protocol: "https"
    load-balancer.hetzner.cloud/certificate-type: "managed"
    load-balancer.hetzner.cloud/http-managed-certificate-domains: "ndx.100days.cloud"
    load-balancer.hetzner.cloud/http-redirect-http: "true"
    load-balancer.hetzner.cloud/http-sticky-sessions: "true"
```

unfortunately the cloud-controller then had an error when trying to ensure the LB:

```
Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBServices: at least one certificate is required for protocol https (invalid_input)
```

what am i missing?

**Comment by exocode** [comment]
I'm not a K8s master, but this tutorial helped me: 

https://community.hetzner.com/tutorials/configure-lb-cert-with-external-domain

**Comment by chwzr** [comment]
You need the annotation `load-balancer.hetzner.cloud/http-certificates` to be set with the name of the certificate in cloud console. (if you created the certificate manual). Or setting `load-balancer.hetzner.cloud/http-managed-certificate-name` with same value will automaticly create the cert under the name. 


E.g. let hetzner-cloud-controller-manager auto create the cert "ndx-100days-cloud-tls" under domain "ndx.100days.cloud" and assign to your service:
```yaml
  annotations:
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/name: ndx
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/protocol: "https"
    load-balancer.hetzner.cloud/certificate-type: "managed"
    load-balancer.hetzner.cloud/http-managed-certificate-domains: "ndx.100days.cloud"
    load-balancer.hetzner.cloud/http-managed-certificate-name: "ndx-100days-cloud-tls"
    load-balancer.hetzner.cloud/http-certificates: "ndx-100days-cloud-tls"
    load-balancer.hetzner.cloud/http-redirect-http: "true"
    load-balancer.hetzner.cloud/http-sticky-sessions: "true"

```
