### ISSUE TITLE
Looking for routing fanout example with type: Ingress not type: Loadbalancer

### ISSUE THREAD

**Issue by exocode** [hetznercloud/hcloud-cloud-controller-manager#227]
Hi there, 

I am searching for an `Ingress` fanout example, something like this: 

Basically I need this: 
```
    /    to APP A 
    /api to APP B
```

How can I achieve that with hcloud-cloud-controller-manager? What part I am missing?

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx // with nginx-ingress-controller installed
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /api
        backend:
          serviceName: backend
          servicePort: 3000
```

1.) Tried to annotate this ingress with that:
2.) also tried this annotations on the ingress controller itself

```yaml
    load-balancer.hetzner.cloud/hostname:  foo.bar.com
    load-balancer.hetzner.cloud/http-certificates: managed-certificate-1-wildcard-bar-com
    load-balancer.hetzner.cloud/name: lb-staging
```

**Which config is the right one?
The [docs](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/v1.7.0/docs/load_balancers.md) saying it's working with `L4 type: Loadbalancer`. How to get `L7 type: Ingress` working?**

Thank you in advance

**Comment by chwzr** [comment]
add the `load-balancer.hetzner.cloud/...` annotations to you ingress-nginx-controller instead. These annotations are for Services of type "LoadBalancer" not for your Ingress definiton. Don't confuse IngressController with Ingress ;)

**Comment by stevek-pro** [comment]
@chwzr Hi could you kindly provide us with a working configuration (controller, ingress, service) and with or without auto-TLS provisioning etc. Nothing for me works so far.

**Comment by exocode** [comment]
This one works for me. 
What you also need if you wanna use TLS is a Issuer or Clusterissuer and a Certificate. I work with cert-manager and Cloudflare. That is my setup:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-staging
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    load-balancer.hetzner.cloud/hostname:  www.example.com
    load-balancer.hetzner.cloud/http-certificates: managed-certificate-1-wildcard-bar-com
    load-balancer.hetzner.cloud/name: lb-staging
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-app
                port:
                  number: 80
          - path: /backend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-app
                port:
                  number: 80
      host: www.example.com
  tls:
    - hosts:
        - "www.example.com"
      secretName: demo-cert-secret
```



```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com-staging
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.example.com"
  dnsNames:
    - example.com
    - "*.example.com"
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: XXXXXXXXXXXX

```

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your@email.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector: {}
        # dnsNames:
        # - example.com
        dns01:
          cloudflare:
            email: mail@jezekjan.com
            # !! Remember to create a k8s secret before
            # kubectl create secret generic cloudflare-api-key-secret
            apiKeySecretRef:
              name: cloudflare-api-token-secret
              key: api-token
```
