### ISSUE TITLE
original client IP

### ISSUE THREAD

**Issue by alrf** [hetznercloud/hcloud-cloud-controller-manager#230]
I have Nginx deployed in my cluster and Service annotations are:
```
  annotations:
    load-balancer.hetzner.cloud/name: "nginx-es-lb"
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/type: "lb11"
    load-balancer.hetzner.cloud/hostname: my.domain.com
    load-balancer.hetzner.cloud/protocol: https
    load-balancer.hetzner.cloud/certificate-type: "uploaded"
    load-balancer.hetzner.cloud/http-certificates: "482204" ### cert ID
```

In nginx logs I see only k8s worker node IPs (and depends on `load-balancer.hetzner.cloud/disable-private-ingress` and `load-balancer.hetzner.cloud/use-private-ip` settings - public or private worker IPs). 
How to change the configuration to see the original client IP? (`X-Forwarded-For` / `Real‑IP`)
