### ISSUE TITLE
hcloud/CreateRoute: invalid gateway (invalid_in put)

### ISSUE THREAD

**Issue by vaisov** [hetznercloud/hcloud-cloud-controller-manager#248]
Using Cilium with wireguard enabled encryption doesn't work with hcloud cloud controller. I'm getting error:

```
E0923 07:24:06.930258       1 route_controller.go:217] Could not create route 1404bb65-7edf-453f-849f-7207e297671c 10.244.0.0/24 for node de-hc-rancher-prod01: hcloud/CreateRoute: invalid gateway (invalid_input)
```

Cilium config I'm using:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  bootstrap: true
  version: "v1.10.3"
  valuesContent: |-
    tunnel: disabled
    nativeRoutingCIDR: "10.0.0.0/8"
    enable-endpoint-routes: "true"
    kube-proxy-replacement: "probe"
    enable-external-ips: "false"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    l7Proxy: false
    encryption:
      enabled: true
      type: wireguard
```
