### ISSUE TITLE
external dns stopped working upgrade from 1.8.1 to 1.12.0

### ISSUE THREAD

**Issue by lachnerd** [hetznercloud/hcloud-cloud-controller-manager#254]
i recently upgraded my setup from ccm 1.8.1 to 1.12.0 using external dns on traefik service.

With 1.8.1

i used this annotations in traefik values.yaml wich worked fine for me
```
service:
  enabled: true
  type: LoadBalancer
  # hetzner only annotations
  annotations: 
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/network-zone: nbg1
    load-balancer.hetzner.cloud/name: traefik-lb
    external-dns.alpha.kubernetes.io/access: public
    external-dns.alpha.kubernetes.io/hostname: traefik.domain.tld
```

Then i switched to 1.12.0 and realized my DNS entries weren't set at all.
```
level=error msg="InvalidChangeBatch: [Invalid Resource Record: 'FATAL problem: ARRDATAIllegalIPv4Address (Value is not a valid IPv4 address) encountered with
```

So i added :
````
load-balancer.hetzner.cloud/ipv6-disabled: true
```

The error is gone but external-dns no tells me, that all entries are in sync and nothing has to be set, and i still got no DNS Entry set for  "traefik.domain.tld".

Any clues whats wrong here?
