### ISSUE TITLE
Loadbalancer ignores targetPort

### ISSUE THREAD

**Issue by Giom-fm** [hetznercloud/hcloud-cloud-controller-manager#259]
I've been trying to get the loadbalancer to work for days. The main problem is that the loadbalancer ignores "targetPort".

Here is my setup:

The echo-deployment.yml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.0
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
```
The echo-service.yml:
```
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echoserver
  ports:
  - port: 80
    targetPort: 8080
```
The ingress.yml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: my.site.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: echo-service
              port:
                number: 80
```
Loadbalancer.yml:
```
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  annotations:
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/name: My-Loadbalancer
    load-balancer.hetzner.cloud/hostname: cluster.site.io
    load-balancer.hetzner.cloud/use-private-ip: "true"
    # Healthcheck
    load-balancer.hetzner.cloud/health-check-protocol: tcp
    load-balancer.hetzner.cloud/health-check-port: "10254"
spec:
  selector:
    app: my-ingress
    app.kubernetes.io/component: controller
    release: ingress
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
```
Basically, everything works. The ingress-controller runs on both nodes and listens on port 80 and 443 and I can curl the echo-service from any node. However, when deploying the loadbalancer, the "targetPort is not taken into account. I did it exactly as stated in the documentation: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/load_balancers.md#sample-service-with-networks
But when I curl my.site.io I get no result.

![image](https://user-images.githubusercontent.com/35076723/142212869-140d83a3-ddc8-45ae-8999-95deead21166.png)

It seems that some random port (from the NodePort range) is used as targetPort. The fact that the healthchecks are green is because the healthcheck-annotation takes the correct value.
If I now manually (hetzner-cloud-gui) change the destination port to the desired port 80, my requests go through and I get a response when curling.

What am I doing wrong here? Why is "targetPort" not taken over? Do I understand the usecase of the loadbalancer wrong? Are annotations missing on the loadbalancer?
