### ISSUE TITLE
Certificate, LB TLS termination and Ingress 

### ISSUE THREAD

**Issue by druppy** [hetznercloud/hcloud-cloud-controller-manager#263]
Hi ...

We have tried to make hcloud LB, using TLS termination and hcloud managed certificates, but with little luck.

We have the following ingress annotations :

```yaml
annotations: 
        load-balancer.hetzner.cloud/location: fsn1
        load-balancer.hetzner.cloud/name: kube-lb
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/disable-private-ingress: "true"
        load-balancer.hetzner.cloud/protocol: "https"

        load-balancer.hetzner.cloud/certificate-type: "managed"
        load-balancer.hetzner.cloud/http-managed-certificate-name: "moch"
        load-balancer.hetzner.cloud/http-managed-certificate-domains: "*.moch.dk,moch.dk"
```
We have an existing cert called "moch" but it can't find this, and it seems to create its own.

The `http-managed-certificate-domains` dislike spaces :-)

It complains about a few things, like

`Error syncing load balancer: failed to ensure load balancer ...: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBServices: hcops/hclbServiceOptsBuilder.buildAddServiceOpts: hcops/CertificateOps.GetCertificateByLabel: Get "https://api.hetzner.cloud/v1/certificates?label_selector=hcloud-ccm%2Fservice-uid%3D4bbd4f00-95a9-4739-b4e6-51dc1366a54a&page=1": context deadline exceeded`

I quess this means this this service `https://api.hetzner.cloud/v1/certificates?label_selector=hcloud-ccm%2Fservice-uid%3D4bbd4f00-95a9-4739-b4e6-51dc1366a54a&page=1"` gave the above error, but what did it mean ?

The other is : Error syncing load balancer 'cannot create more than 20 managed certificates per hour (resource_limit_exceeded)' 

This makes sense of a kind, but I have a feeling it is asking many time while starting up ? I may need to wait an hour before this works, but it really should have reused the existing cert, as far as I see.

Does this mean that it would be more safe to use `hcloud` LB as a plain layer 3 tcp LB, and let ingress handle TLS instead ?

I am looking forward info to resolve this :-)

**Comment by stevek-pro** [comment]
I can confirm this, that it creates certs on its own and ignores names. I provide certs in LB manually therefore until this is fixed or clarified where we go wrong. Also one of my LBs autmatically gets created withit my consent, but must be some old resource provisioning it. I switched of Ingress and using Service and NodePort now. Good luck!

**Comment by druppy** [comment]
Ok, thanks ... I will try to use it as a pure level 3 LB, and let ingress take over cert management.

I really hoped to get some kind of status from Hetzner in regard to LB, as this is the last element vi need for a successful setup (we have a k8s 1.22 with autoscale and cilium cni, and this is the last part missing).

**Comment by LKaemmerling** [comment]
Hey @druppy & @stevek-pro,

when you set those annotations:
```
     load-balancer.hetzner.cloud/certificate-type: "managed"
        load-balancer.hetzner.cloud/http-managed-certificate-name: "moch"
        load-balancer.hetzner.cloud/http-managed-certificate-domains: "*.moch.dk,moch.dk"
 ```
The CCM tries to create this certificate. If you want to reference an already existing certificate you need to use:

```
load-balancer.hetzner.cloud/http-certificates: "<id or name of your cert>"
```
https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/internal/annotation/load_balancer.go#L119

**Comment by druppy** [comment]
@LKaemmerling thanks for you input, this would be nice if this worked, I dont mind defining a named certificate by hand, as this is a one time action :-)

I added a certificate called "moch" in hcloud and these annotations on ingress

``` yaml
load-balancer.hetzner.cloud/location: fsn1
load-balancer.hetzner.cloud/name: kube-lb
load-balancer.hetzner.cloud/http-certificates: "moch"
```
But the ingress server is not happy, as it complains : 

```
Error syncing load balancer: 
    failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: 
       hcops/LoadBalancerOps.ReconcileHCLBServices: invalid input in field 'http' (invalid_input)
```

I tried to find the `LoadBalancerOps.ReconcileHCLBServices` in the CCM code, without luck so I not sure what is missing.

Also, will this certificate be setup only for `https`, and will any other services defined in `tcp.ports` become pure tcp pass through ?
