### ISSUE TITLE
Hetzner LB targets still unhealthy 

### ISSUE THREAD

**Issue by sitamoni** [hetznercloud/hcloud-cloud-controller-manager#270]
Hi Admins.
I have an issue with setting up LB in kubernetes. The hetzner-cloud-controller-manager is done and till kubectl ccm.yaml.
I created ingress-nginx and the pods are running successfully with "kubectl get pods -n kube-system".
The services are:
```
NAME                                                  TYPE           CLUSTER-IP      EXTERNAL-IP                        PORT(S)                      AGE
kubernetes                                            ClusterIP      10.233.0.1      <none>                             443/TCP                      11d
nginx-controller-ingress-nginx-controller             LoadBalancer   10.233.10.211   xxxxxxxxxxxxxxx::1,xxxxxxxxx   80:30858/TCP,443:32681/TCP   11d
nginx-controller-ingress-nginx-controller-admission   ClusterIP      10.233.25.112   <none>                             443/TCP                      11d
```
All the master and nodes are connected via terraform created network except LB. But i still dont know why the services are unhealthy check.  With kubectl logs there are no failure and the pod of kube-system has only` Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is`. And if i provide curl or IP of the node i got the answer but with LB IPv4 public this is still responding with empty reply from server

Any Idea ?

**Comment by fhofherr** [comment]
Hi,

based on the provided information it is hard to analyze the issue. What we would need is a minimal working example showing what you try to achieve and what did not work. Can you please provide such an example?

**Comment by Shadowghost** [comment]
Did you properly label the master nodes to be not included in the load-balancing (see https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/182#issuecomment-830577642)?

**Comment by sitamoni** [comment]
Thanks for trying to help. I could sole the issue by adding the following line into my values.yaml file for the helm chart at the annotations field:
`load-balancer.hetzner.cloud/hostname: test1.as-servertest.net`
Afterwards i get now the External IP the domain which has LB IP set:
```
kubernetes                                            ClusterIP      10.233.0.1     <none>                    443/TCP                      26h
nginx-controller-ingress-nginx-controller             LoadBalancer   10.233.48.38   test1.<domain>.net   80:32113/TCP,443:30946/TCP   3h19m
nginx-controller-ingress-nginx-controller-admission   ClusterIP      10.233.34.49   <none>                    443/TCP                      3h19m
```
Now all services created are healthy on the hetzner cloud console. But by refreshing the domain used and website i still get page not found 404. How to reproduce in this case?

**Comment by AzSiAz** [comment]
In case you still need it, here is my ingress-nginx value.yaml
```yaml
tcp:
  5432: "spirit-dev/pg-dev-postgresql-ha-pgpool:5432"
controller:
  nodeSelector:
    hcloud/node-group: default
  ingressClassResource:
    enabled: true
    name: nginx-global
  metrics:
    enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  config:
    use-proxy-protocol: "true"
  service:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: "Cluster"
    external:
      enabled: true
    annotations:
      load-balancer.hetzner.cloud/location: ${LB_LOCATION}
      load-balancer.hetzner.cloud/name: nginx-global
      load-balancer.hetzner.cloud/use-private-ip: true
      load-balancer.hetzner.cloud/disable-private-ingress: true
      load-balancer.hetzner.cloud/http-redirect-http: true
      load-balancer.hetzner.cloud/uses-proxyprotocol: true
```
Setting `externalTrafficPolicy` to `Local` make health status mixed with only deployed node reachable
`Cluster` make LB healthy for all targets

What allowed my service to not make ssl or not found error is proxy pass stuff, external-dns+cert-manager and not hostname annotation

The only thing not working is postgres with tcp passthrough, still don't know why for now

Hope it help you
