### ISSUE TITLE
Basic deployment (without Networks support) does not work

### ISSUE THREAD

**Issue by windsource** [hetznercloud/hcloud-cloud-controller-manager#30]
I am trying to setup hcloud-cloud-controller-manager without Networks support using

```bash
kubectl apply -f  https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/master/deploy/v1.5.0.yaml
```

but it fails with pod being in state CreateContainerConfigError due a missing secret:

```text
Error: couldn't find key network in Secret kube-system/hcloud
```

Actually I have only created `token` but not `network` because I didn't want to use the Networks feature. Is the deployment manifest wrong or how can I solve that?

**Comment by driehle** [comment]
I had the same issue. Manually adding the key `network` to the `hcloud` secret with an empty value helps at least with starting the container...

**Comment by markkutikkanen** [comment]
Same issue here.

**Comment by identw** [comment]
Just remove from the environment:
```
            - name: HCLOUD_NETWORK
              valueFrom:
                secretKeyRef:
                  name: hcloud
                  key: network
```
