### ISSUE TITLE
Setting IPv4 RDNS has no impact

### ISSUE THREAD

**Issue by DrBu7cher** [hetznercloud/hcloud-cloud-controller-manager#310]
If you specify IPv4 RDNS it does neither change the existing one on the loadbalancer nor create a new one correctly.

**Comment by tomsiewert** [comment]
Most likely fixed with #315

**Comment by DrBu7cher** [comment]
I don't know if this is related to the linked PR, but I now cannot get my Loadbalancer to work.
I see the following:
```bash
NAME                       TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
nginx-ingress-controller   LoadBalancer   10.43.139.10   <pending>     80:31155/TCP,443:32532/TCP   5m22s
```
Why is the external IP pending? The Loadbalancer is being created but no targets are being assigned. The age is 5m22s, because it is my clean-install test. I created a whole new cluster with flux and helm, so my configuration did not change. But the behaviour of the HCloud LB did. Can you give me a hint what else to try? I will wait longer, but I am not expecting it to work, since it didn't work after me waiting about an hour.

**Comment by tomsiewert** [comment]
Could you please post the configuration of your HelmRelease or of your LoadBalancer service? Are there any obvious errors in the CCM logs?

**Comment by DrBu7cher** [comment]
My nginx-ingress-controller release.yaml:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "9.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
    disableWait: true
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    service:
      type: LoadBalancer
      annotations:
        load-balancer.hetzner.cloud/location: fsn1
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/name: "api-lb01"
        load-balancer.hetzner.cloud/ipv4-rdns: "test.example.com" # redacted domain
```
