### ISSUE TITLE
Annotation `ipv6-disabled` has no effect. 

### ISSUE THREAD

**Issue by mkanderson** [hetznercloud/hcloud-cloud-controller-manager#326]
I'm trying to set up `external-dns`  using an Hetzner LB. As recommended in the [source code](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/2538d3ac41d7c62bdb94a103099dda58be3a4f3e/internal/annotation/load_balancer.go#L34), I've set the `ipv6-disabled` option:

```
apiVersion: v1
kind: Service
metadata:
  name: echo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo2.mydomain.site
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/disable-private-ingress: "true"

spec:
  selector:
    app: echo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
```
However, this seems to have no effect. The IPv6 Address still appears in the service as an external IP, causing pdns to throw a fit and fail with a 422. 
```
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP                                    
echo         LoadBalancer   10.102.31.133    142.132.240.29,2a01:4f8:c01e:e9::1
```
/A '2a01:4f8:c01e:e9::1': Parsing record content (try 'pdnsutil check-zone'): unable to parse IP address, strange character: a\"}"
```
