### ISSUE TITLE
Problem with http-https redirection

### ISSUE THREAD

**Issue by tagurus** [hetznercloud/hcloud-cloud-controller-manager#333]
Hello, i encountered with problem. 
Hetzner lb haz ability to terminate https, by adding annotation
(my config nginx-ingress-controller 1.5.1)

apiVersion: v1
kind: Service
metadata:
  annotations:
    load-balancer.hetzner.cloud/name: "cluster-lb"
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/protocol: "https"
    load-balancer.hetzner.cloud/http-certificates: "***"
    load-balancer.hetzner.cloud/http-redirect-http: "true"

[hetzner lb services](https://gyazo.com/4eddff7f437aceec7605fc5fae2cb94d)

But after that has error in ingress

`Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBServices: port 80 is busy, redirect_http is enabled on another service (source_port_already_used)`

any idea about this feature?

**Comment by apricote** [comment]
Hey @tagurus,

this is unfortunately a little bit complicated and confusing right now. I built this example, using the `ingress-nginx` Helm Chart to configure it. If you you something else, you might need to check how to configure it similarly.

Helm Values:
```
controller:
  service:
    annotations:
      load-balancer.hetzner.cloud/name: test-http-redirect

      load-balancer.hetzner.cloud/location: hel1
      load-balancer.hetzner.cloud/protocol: https

      load-balancer.hetzner.cloud/certificate-type: managed
      load-balancer.hetzner.cloud/http-managed-certificate-name: test-http-redirect
      load-balancer.hetzner.cloud/http-managed-certificate-acme-staging: "true"
      load-balancer.hetzner.cloud/http-managed-certificate-domains: julian-test-http-redirect.hc-certs.de

      load-balancer.hetzner.cloud/http-redirect-http: "true"

      load-balancer.hetzner.cloud/health-check-protocol: http
      load-balancer.hetzner.cloud/health-check-http-domain: julian-test-http-redirect.hc-certs.de
      load-balancer.hetzner.cloud/health-check-http-path: /
      load-balancer.hetzner.cloud/http-status-codes: 200,404


    enableHttps: false
    ports:
      # We use http between load-balancer and the ingress, but hccm exposes the listen port
      # to the public, where we want https.
      http: 443
```

Install/upgrade:
```
helm upgrade --install ingress-nginx ingress-nginx \                                                                                                                        kubernetes-helm
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace -f ./ingress-nginx.values.yaml
```

Resulting kubernetes service:

```
