### ISSUE TITLE
ExternalP still required when running Calico instead of flannel

### ISSUE THREAD

**Issue by loxal** [hetznercloud/hcloud-cloud-controller-manager#40]
I am running the latest hcloud-cloud-controller-manager, with Calico v3.13.2, and K8s v1.18.2 which gives me  `1020 ?        Ssl    3:41 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --cloud-provider=external`

I still need to specify the explicit `externalIPs` entry. 

```
kind: Service
apiVersion: v1
metadata:
  name: router
spec:
  selector:
    app: router
  ports:
    - port: 80
      name: unencrypted
    - port: 443
      name: encrypted
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 99.99.99.99
```

When I do not specify the IP, I get 
```
default       service/router                          LoadBalancer   10.109.138.114   <pending>     80:31869/TCP,443:32569/TCP   3d4h
```

...which stays pending and the router is not reachable. Is this issue on your radar or can you advice me how I can get rid of the specific IP from my spec. Eventually I want to propagate the client IPs to a pod inside K8s cluster. Therefore I have specified  `externalTrafficPolicy: Local` which does not have any effect. I assume that this is due to the specific IP address specification.
