### ISSUE TITLE
existing load-balancer is not picked up

### ISSUE THREAD

**Issue by schlichtanders** [hetznercloud/hcloud-cloud-controller-manager#504]
Hello,
I am using hccm via kube-hetzner and run into a weird behaviour that the load-balancer configured on traefik loadbalancer service as
```yaml
annotations:
    load-balancer.hetzner.cloud/algorithm-type: round_robin
    load-balancer.hetzner.cloud/disable-private-ingress: 'true'
    load-balancer.hetzner.cloud/disable-public-network: 'false'
    load-balancer.hetzner.cloud/health-check-interval: 15s
    load-balancer.hetzner.cloud/health-check-retries: '3'
    load-balancer.hetzner.cloud/health-check-timeout: 10s
    load-balancer.hetzner.cloud/hostname: cloud.jolin.io
    load-balancer.hetzner.cloud/ipv6-disabled: 'false'
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/name: jolin-20230906t133532z
    load-balancer.hetzner.cloud/type: lb11
    load-balancer.hetzner.cloud/use-private-ip: 'true'
    load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
```
is not picking up on a pre-existing load-balancer `jolin-20230906t133532z`, but creates a new one in the wrong location (fsn1) and with a wrong name (jolin). Neither information I have a clue where it could have taken it from.

The final result are two load-balancers, one active with the wrong name and location, the other useless.
![image](https://github.com/hetznercloud/hcloud-cloud-controller-manager/assets/4255480/90106311-a105-4dbf-81d7-b3a52b8d5adf)
- looking at the times, it can also be confirmed that the wrong one was indeed deployed after the pre-existing load-balancer.

I also experienced one other weird behaviours, probably related. If I deploy a second cluster into the same hetzner project (making sure all names are different), everything is indeed duplicated, but not this very load-balancer. It somehow picked up the previous one and renamed it.

Any help is highly appreciated.
I am using the most recent ccm version v1.17.2
