### ISSUE TITLE
Calico and HCC

### ISSUE THREAD

**Issue by medicol69** [hetznercloud/hcloud-cloud-controller-manager#641]
### TL;DR

This is more of an inquiry, since it's not that clear from the documentation, does the hetzner cloud controller work with the Calico CNI when using the private interfaces on Hetzner? Thanks

### Expected behavior

this is an inquiry on the documentation.

**Comment by apricote** [comment]
When you use the private networks from Hetzner Cloud with hcloud-cloud-controller-manager and enable the routes-controller (default), then you should be able to use Calico without any additional overlay networks. You can configure this in Calico with [`CALICO_NETWORKING_BACKEND=none`](https://docs.tigera.io/calico/latest/reference/configure-calico-node)

I have never personally tested this configuration though.

**Comment by simonostendorf** [comment]
I am also interested in this topic, if you have any knowledge @medicol69 please let me now :)

**Comment by DeprecatedLuke** [comment]
Yes, it works fine with calico. To run a quick test use [hetzner-k3s](https://github.com/vitobotta/hetzner-k3s).

Important warning when running cloud together when baremetal. Calico requires a /24 vlan address **per node** which means when you're creating a subnet **make sure** the vlan subnet is at minimum a /23 (2 nodes max) or ideally /17 (128 nodes max) allocating first half to cloud instances and the second half to baremetal instances.

**Comment by medicol69** [comment]
thanks, but I don't think that the hetzner private network interfaces are stable enough to use them in production. If anyone got them to work and give out an example of how to use it in prod I'm all ears.

**Comment by DeprecatedLuke** [comment]
I am currently running it just fine with calico and even have ceph working over vlan with pretty good performance. You cannot advertise nodeip with internal so define hostendpoint instead for metrics and etcd to be protected. Load balancers also require you to use public net in this case.

**Comment by simonostendorf** [comment]
I am using calico without encapsulation and hccm with routes enabled. I think this works well, but I haven't tested it enough to be 100% sure.

If you have any feedback on this configuration, I would love to discuss it :)

`calico-tigera-operator-values.yaml`
```
installation:
  cni:
    type: Calico
    ipam:
      type: HostLocal # use podCIDR assigned by kube-controller-manager, that is also used by route-controller in hcloud-cloud-controller-manager
  calicoNetwork:
    bgp: Enabled
    linuxDataplane: BPF
    hostPorts: Disabled
    ipPools:
      - name: default-ipv4
        cidr: 10.0.0.0/16
        encapsulation: None
        blockSize: 24
        natOutgoing: Enabled
        nodeSelector: all()
defaultFelixConfiguration:
  enabled: true
  bpfEnabled: true
  bpfExternalServiceMode: DSR
  bpfKubeProxyIptablesCleanupEnabled: true
kubernetesServiceEndpoint:
  host: api.my-cluster.domain.tld
  port: 6443
```
