### ISSUE TITLE
CCM with Hetzner network attempts to create IPv6 routes

### ISSUE THREAD

**Issue by Xinayder** [hetznercloud/hcloud-cloud-controller-manager#659]
### TL;DR

Setting up a dual stack k8s cluster with HCCM and Hetzner's inter-server networking will result in the CCM attempting to create IPv6 routes for the internal Hetzner network.

### Expected behavior

IPv6 routes should be created normally.

### Observed behavior

The cloud controller keeps trying to create an IPv6 route on a v4 only network, failing with the error: 
`Could not create route <route-id> 2001:cafe:42::/64 for node <node_name>: hcloud/CreateRoute invalid input in field 'destination' (invalid_input)`

### Minimal working example

Setup k3s with:

```yaml
disable-cloud-controller: true
disable-network-policy: true
kubelet-arg: "cloud-provider=external"
cluster-init: true
cluster-cidr: 10.42.0.0/16,2001:cafe:42::/56
service-cidr: 10.43.0.0/16,2001:cafe:43::/112
```

Setup a Hetzner network with address `10.0.0.0/24`

### Log output

```plain text
`Could not create route <route-id> 2001:cafe:42::/64 for node <node_name>: hcloud/CreateRoute invalid input in field 'destination' (invalid_input)`
```
