### ISSUE TITLE
ingress controller 

### ISSUE THREAD

**Issue by vukomir** [hetznercloud/hcloud-cloud-controller-manager#74]
Hi,

Is it posible to use LB as a ingress controller so you don't need to create a LB for every service?

Thanks,
Vuko

**Comment by fhofherr** [comment]
Hi @vukomir, I guess you could try putting the LB before your ingress controller.

**Comment by MatthiasLohr** [comment]
A LoadBalancer is a special type of a service (traffic redirection), an ingress controller is a special type of software running in your Kubernetes environment. So you can't (never) use a LoadBalancer/Service as an Ingress Controller, because it's completely different.

However, the idea of @fhofherr works like a charm: Install an Ingress Controller (e.g. nginx-ingress), and give it a Service type LoadBalancer. E.g., when you want to use the nginx-ingress helm chart, you can use a configuration similar to this one:
```yaml
controller:
  config:
    use-proxy-protocol: "true"
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: k8s1lb1
      load-balancer.hetzner.cloud/location: fsn1
      load-balancer.hetzner.cloud/use-private-ip: true
      load-balancer.hetzner.cloud/algorithm-type: least_connections
      load-balancer.hetzner.cloud/uses-proxyprotocol: true
      load-balancer.hetzner.cloud/hostname: k8s1lb1.example.com
```
Then, if you have the hcloud-cloud-controller-manager installed, it will create the LoadBalancer for you, forwards the traffic to nginx-ingress and nginx-ingress will do the rest.

**Comment by laukaichung** [comment]
Hi @MatthiasLohr 
I try to follow your suggestion to install Ingress Nginx:

````
controller:
  config:
    use-proxy-protocol: "true"
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: nginx-controller-new
      load-balancer.hetzner.cloud/location: hel1
      load-balancer.hetzner.cloud/algorithm-type: least_connections
      load-balancer.hetzner.cloud/uses-proxyprotocol: true
      load-balancer.hetzner.cloud/http-redirect-https: 'false'
```` 

I also use this [repo](https://github.com/hershkoy/magento2-on-kubernetes/tree/7dc2e4d409b863ac88619e3067ec8f80638a2711/deploy/bases/app) as a reference. Here is what I have:

````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  replicas: 3
  template:
    metadata:
      labels:
        app: echo1
    spec:
      containers:
        - name: echo1
          image: hashicorp/http-echo
          args:
            - "-text=echo1 deployment"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5678

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: echo-service
      port:
        name: http
````
The 32740 and 32537 are ports to ingress controller pods but the health checks all fail
![Image Info](https://i.ibb.co/zHRMWQm/Screenshot-2021-05-30-11-01-49.png)

What I don't understand is how Ingress Nginx connects to echo service? The Ingress kind doesn't work.
