### ISSUE TITLE
Don't add nodes with some service label to load balancer target

### ISSUE THREAD

**Issue by jekakm** [hetznercloud/hcloud-cloud-controller-manager#75]
Would be cool if I have ability to label node with some service label and this node will be ignored and not added as target in load balancer. For example - I have 4 nodes for Ingress controller, that use this loadbalanser and have another 100 nodes, that do not. And I dont want to all this nodes will be added as targets in LB

**Comment by saltenhub** [comment]
That would be super helpful. We have a cluster of dedicated and cloud nodes and clearly the LoadBalancer does not support the dedicated nodes.

**Comment by LKaemmerling** [comment]
K8s is in favor of handling what nodes should be attached. We just get a list of nodes from k8s: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/hcloud/load_balancers.go#L72 

So, unfortunately, this is out of our scope.

**Comment by tobiaskohlbau** [comment]
I want to add some value to his:

As of kubernetes 1.16 there exists a feature gate [_ServiceNodeExclusion_](https://v1-16.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) which should make the exlusion of special nodes possible:
>ServiceNodeExclusion: Enable the exclusion of nodes from load balancers created by a cloud provider. A node is eligible for exclusion if labelled with “alpha.service-controller.kubernetes.io/exclude-balancer” key (when LegacyNodeRoleBehavior is on) or node.kubernetes.io/exclude-from-external-load-balancers

**Comment by lucatk** [comment]
@tobiaskohlbau have you managed to get this to work with HCloud load balancers? I have enabled the feature gate and tried both labels, none yielding any change in which nodes are applied as targets...

**Comment by tobiaskohlbau** [comment]
Yes I managed to get it working.

Please notice that _hcloud-cloud-controller-manager_ is responsible for managing these feature (to be specific the underlying library k8s.io/cloud-provider).
Therefore the right place to apply the feature gate is within the deployment of _hcloud-cloud-controller-manager_ itself instead of the apiserver or other components.

For e.g. my deployment contains:
```YAML
containers:
        - image: hetznercloud/hcloud-cloud-controller-manager:v1.6.1
          name: hcloud-cloud-controller-manager
          command:
            - "/bin/hcloud-cloud-controller-manager"
            - "--cloud-provider=hcloud"
            - "--leader-elect=false"
            - "--allow-untagged-cloud"
            - "--allocate-node-cidrs=true"
            - "--cluster-cidr=10.129.0.0/17"
            - "--feature-gates=ServiceNodeExclusion=true"
```
