### ISSUE TITLE
Robot Servers InternalIP is not set in node manifest

### ISSUE THREAD

**Issue by mehrdadpfg** [hetznercloud/hcloud-cloud-controller-manager#760]
### TL;DR

Dedicated Servers InternalIP should be set in the node manifests like the cloud servers. It is an important bug since metrics-server can not reach the servers and also the kubelet has been configured by the InternalIP.( --node flag )

### Expected behavior

```
status:
  addresses:
  - address: x.x.x.x
    type: InternalIP
  - address: k8s-node
    type: Hostname
  - address: x.x.x.x.
    type: ExternalIP
 ```
 expected to see the internalIP in the dedicated servers as well

### Observed behavior

```
status:
  addresses:
  - address: k8s-node
    type: Hostname
  - address: x.x.x.x.
    type: ExternalIP
 ```

### Log output
constantly trying to find the dedicated server privateIP in cloud
```plain text
 19:14:35.804948       1 node_controller.go:389] Failed to update node addresses for node "k8s-node": failed to get node address from cloud provider that matches ip: x.x.x.x
```
