### ISSUE TITLE
Load balancer being provisioned without targets

### ISSUE THREAD

**Issue by ktalap** [hetznercloud/hcloud-cloud-controller-manager#769]
### TL;DR

It all works good if I add the target to my node manually in hetzner. Otherwise, all the ports and everything are set but the target to the node. Here is the logs of the controller:

```
 kubectl logs -n kube-system -l app=hcloud-cloud-controller-manager --tail=100 -f
```

I1027 15:16:52.858565       1 event.go:307] "Event occurred" object="default/web-app" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
I1027 15:16:52.878447       1 load_balancers.go:109] "ensure Load Balancer" op="hcloud/loadBalancers.EnsureLoadBalancer" service="web-app" nodes=[]
I1027 15:16:52.879167       1 event.go:307] "Event occurred" object="default/web-app" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="UnAvailableLoadBalancer" message="There are no available nodes for LoadBalancer"
I1027 15:16:53.741870       1 route_controller.go:216] action for Node "node1" with CIDR "10.233.64.0/24": "keep"
I1027 15:16:55.376856       1 load_balancer.go:723] "add service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=80 loadBalancerID=2127367
I1027 15:16:56.411260       1 load_balancers.go:159] "reload HC Load Balancer" op="hcloud/loadBalancers.EnsureLoadBalancer" loadBalancerID=2127367
I1027 15:16:56.589854       1 event.go:307] "Event occurred" object="default/web-app" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"

Doesn't look like it's failing or anything. Here is the cluster config for the kubespray:
```
cloud_provider: external
external_cloud_provider: hcloud

external_hcloud_cloud:
  token_secret_name: hcloud-api-token
  with_networks: true
  service_account_name: hcloud-sa
  hcloud_api_token: "{{ lookup('env', 'HCLOUD_API_TOKEN') }}"
  controller_image_tag: v1.16.0

kube_network_plugin: cilium
network_id: kubernetes-node-network
```

```
all:
  hosts:
    node1:
      ansible_host: 172.16.0.101
      ip: 172.16.0.101
      access_ip: 172.16.0.101
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
```

![image](https://github.com/user-attachments/assets/d7c1e7f3-a1d8-49ae-b56a-b3548e903ca9)

### Expected behavior

Supposed to add the internal target to the node that is running the pod.

### Observed behavior

Doesn't add anything to the targets.
