### ISSUE TITLE
`hcloud-csi-node` failing with `robots.enabled: true`

### ISSUE THREAD

**Issue by pat-s** [hetznercloud/hcloud-cloud-controller-manager#779]
### TL;DR

`hcloud-csi` fails to start with `robots.enabled: true` of HCCM

### Expected behavior

`hcloud-csi` runs healthy

### Observed behavior

```yml
        networking:
          enabled: true
        monitoring:
          enabled: false
        robot:
          enabled: true

        args:
          allocate-node-cidrs: 'true'
          cluster-cidr: '10.42.0.0/16'

        env:
          HCLOUD_LOAD_BALANCERS_ENABLED:
            value: 'true'
          HCLOUD_LOAD_BALANCERS_LOCATION:
            value: 'fsn1'
          HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP:
            value: 'true'
          HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS:
            value: 'true'
          HCLOUD_NETWORK_ROUTES_ENABLED:
            value: 'false'
```

Running k3s-agent on the AX42 node. It successfully joined the cluster and hccm seems to have populated the metadata

```
 Labels:             beta.kubernetes.io/arch=amd64                                                                                                                                                        │
│                     beta.kubernetes.io/instance-type=AX42                                                                                                                                                │
│                     beta.kubernetes.io/os=linux                                                                                                                                                          │
│                     failure-domain.beta.kubernetes.io/region=fsn1                                                                                                                                        │
│                     failure-domain.beta.kubernetes.io/zone=fsn1-dc12                                                                                                                                     │
│                     k3s_upgrade=true                                 
```

However, `hcloud-csi-node` for this node fails with

```
hcloud-csi-driver level=error ts=2024-11-05T09:33:09.937702492Z msg="failed to fetch server ID from metadata service" err="Get \"http://169.254.169.254/hetzner/v1/metadata/instance-id\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

[...]

1 connection.go:173] Still connecting to unix:///run/csi/socket
```

Is this an error on the node configuration in k3s or related to hccm?

Any help is appreciated!

### Log output

```plain text
k3s agent config:


"flannel-iface": "enp6s0"
"kubelet-arg":
- "cloud-provider=external"
- "volume-plugin-dir=/var/lib/kubelet/volumeplugins"
- "kube-reserved=cpu=50m,memory=300Mi,ephemeral-storage=1Gi"
- "system-reserved=cpu=250m,memory=6000Mi"
"node-label":
- "k3s_upgrade=true"
"node-taint": []
"selinux": true
"server": "https://10.255.0.101:6443"
"token": "$TOKEN"
```
```


### Additional information

_No response_
