### ISSUE TITLE
Robot servers cannot be initialised

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hetznercloud/hcloud-cloud-controller-manager#790]
### TL;DR

```
E1112 22:16:14.736364       1 node_controller.go:240] error syncing 'XXX': failed to get node modifiers from cloud provider: provided node ip for node "XXX" is not valid: failed to get node address from cloud provider that matches ip: 10.103.1.103, requeuing
```

### Expected behavior

Robot servers with no taints

### Observed behavior

As described above

### Additional information

```
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: HCLOUD_LOAD_BALANCERS_LOCATION
          value: hel1
        - name: HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP
          value: "true"
        - name: HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS
          value: "true"
        - name: HCLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hcloud
        - name: HCLOUD_NETWORK
          valueFrom:
            secretKeyRef:
              key: network
              name: hcloud
        - name: HCLOUD_NETWORK_ROUTES_ENABLED
          value: "false"
        - name: ROBOT_ENABLED
          value: "true"
        - name: ROBOT_USER
          valueFrom:
            secretKeyRef:
              key: robot_username
              name: hcloud
        - name: ROBOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: robot_password
              name: hcloud
```
