### ISSUE TITLE
Ignores targetPort completely

### ISSUE THREAD

**Issue by nusratulhassan** [hetznercloud/hcloud-cloud-controller-manager#845]
### TL;DR

I have hosted my CNPG cluster control plane node in hetzner. The rest of my applications are non-kubernets or different Kubernetes setups. 
everything works fine except destination_port is created randomly. I have to manually edit LB service to set as per targetPort.
 

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: production-db-ddd-lb
  namespace: prod
  annotations:
    load-balancer.hetzner.cloud/location: ash
    load-balancer.hetzner.cloud/name: cnpg-dd-prod-lb
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: production-db-ddd
    cnpg.io/instanceRole: primary
  ports:
    - name: cnpg-primary
      port: 5432
      targetPort: 5432
      protocol: TCP
EOF
```

### Expected behavior

expecting destination_port to be exactly same defined targetPort following example.
https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md#sample-service

### Observed behavior

<img width="391" alt="Image" src="https://github.com/user-attachments/assets/e640a0ea-c8c5-40be-82b1-f8acdb820836" />

### Log output

```plain text

```
