### ISSUE TITLE
hcops/LoadBalancerOps.ReconcileHCLBServices: port 80 is busy, redirect_http is enabled on another service

### ISSUE THREAD

**Issue by cytrinox** [hetznercloud/hcloud-cloud-controller-manager#916]
I've installed hccm and ingress-nginx on my k3s-driven cluster. While Hetzner LB and ingress-nginx seems to work, I've found this event log:

```
# kubectl events -A --watch
nginx         10s (x294 over 24h)     Warning   SyncLoadBalancerFailed   Service/ingress-nginx-controller                       (combined from similar events): Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBServices: port 80 is busy, redirect_http is enabled on another service (source_port_already_used, 89279ace3d9904c)
```
I've installed ingress-nginx with helm and used these annotations:

```
    annotations:
      load-balancer.hetzner.cloud/name: "mylogin-stage-nginx-lb"
      load-balancer.hetzner.cloud/location: "nbg1"
      # LB must be accessible via public v4/v6
      load-balancer.hetzner.cloud/disable-public-network: "false"
      # Use internal network for host communication
      load-balancer.hetzner.cloud/use-private-ip: "true"
      # Don't forget to configure ingress-nginx to service in PROXYPROTOCOL mode
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      # For k3s setups: only add nodes with agent (skip server nodes)
      load-balancer.hetzner.cloud/node-selector: "k8s.mycompany.dev/k3s-role=agent"
      load-balancer.hetzner.cloud/protocol: "https"
      load-balancer.hetzner.cloud/algorithm-type: "round_robin"
      load-balancer.hetzner.cloud/type: "lb11"
      load-balancer.hetzner.cloud/http-cookie-name: "LB_STICKY_SESSION"
      load-balancer.hetzner.cloud/http-cookie-lifetime: "300s"
      #load-balancer.hetzner.cloud/disable-private-ingress: "true"
      load-balancer.hetzner.cloud/certificate-type: "managed"
      load-balancer.hetzner.cloud/http-redirect-http: "true"
      load-balancer.hetzner.cloud/http-sticky-sessions: "true"
      load-balancer.hetzner.cloud/http-managed-certificate-name: "login-lbcert"
      load-balancer.hetzner.cloud/http-managed-certificate-domains: "login.mycompany.dev"
      # just check if Ingress is running, no need for http check
      load-balancer.hetzner.cloud/health-check-protocol: "tcp"
      load-balancer.hetzner.cloud/health-check-interval: "25s"
      load-balancer.hetzner.cloud/health-check-timeout: "10s"
      load-balancer.hetzner.cloud/health-check-retries: "3"
```

Hetzner LB should terminate HTTPS/TLS traffic, so ingress-nginx only has to provide HTTP.

Because of this, I've setup my values.yml for ingress-nginx chart as follows:

```
controller:
   enableHttp: true
    # -- Enable the HTTPS listener on both controller services or not.
    enableHttps: false
    ports:
      # -- Port the external HTTP listener is published with.
      http: 80
      # -- Port the external HTTPS listener is published with.
      https: 443
    targetPorts:
      # -- Port of the ingress controller the external HTTP listener is mapped to.
      http: http
      # -- Port of the ingress controller the external HTTPS listener is mapped to.
      https: http # <-- HINT: I've changed this by intention as I expected I need to explicitly map https->http
```

After discovery of the warning event, I've modified my values.yml and reinstalled the chart again.  The new values which don't trigger the warning event are:

```
controller:
    enableHttp: false # <-- HINT: now HTTP is disabled
    # -- Enable the HTTPS listener on both controller services or not.
    enableHttps: true # <-- HINT: now HTTPS is enabled
    ports:
      # -- Port the external HTTP listener is published with.
      http: 80
      # -- Port the external HTTPS listener is published with.
      https: 443
    targetPorts:
      # -- Port of the ingress controller the external HTTP listener is mapped to.
      http: http
      # -- Port of the ingress controller the external HTTPS listener is mapped to.
      https: http # <-- HINT: still mapping https to http
```

**I'm not sure why I've to disable HTTP and enable HTTPS for ingress-nginx controller, as I expected it should be vice versa - but it works and prevents the described sync error.**

Maybe hccm devs can give some hints about the "correct" way to configure TLS termination with hccm and ingress-nginx. Motivation for this issue was providing help to other users as google returns nothing for this specific error.

```
$ helm  list -A
NAME                	NAMESPACE           	REVISION	UPDATED                                 	STATUS  	CHART                                 	APP VERSION
hccm                	kube-system         	3       	2025-04-25 11:50:56.855746741 +0200 CEST	deployed	hcloud-cloud-controller-manager-1.24.0	           
hcloud-csi          	kube-system         	1       	2025-04-25 16:29:12.234673963 +0200 CEST	deployed	hcloud-csi-2.13.0                     	           
ingress-nginx       	nginx               	37      	2025-04-28 14:08:41.82840647 +0200 CEST 	deployed	ingress-nginx-4.12.1                  	1.12.1     
kubernetes-dashboard	kubernetes-dashboard	1       	2025-04-27 14:36:28.064951808 +0200 CEST	deployed	kubernetes-dashboard-7.12.0           
```
