### ISSUE TITLE
better documentation for passing values to helm chart

### ISSUE THREAD

**Issue by gecube** [hetznercloud/hcloud-cloud-controller-manager#951]
### TL;DR

I used the next helm values:

```
monitoring:
  enabled: true
  podMonitor:
    enabled: true
env:
  HCLOUD_TOKEN:
    valueFrom:
      secretKeyRef:
        name: hcloud
        key: token
  ROBOT_USER:
    valueFrom:
      secretKeyRef:
        name: hcloud
        key: robot-user
        optional: true
  ROBOT_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: hcloud
        key: robot-password
        optional: true
  HCLOUD_LOAD_BALANCERS_LOCATION: hel1
```

It gave error when applied. And I understood that the correct one is:

```
monitoring:
  enabled: true
  podMonitor:
    enabled: true
env:
  HCLOUD_TOKEN:
    valueFrom:
      secretKeyRef:
        name: hcloud
        key: token
  ROBOT_USER:
    valueFrom:
      secretKeyRef:
        name: hcloud
        key: robot-user
        optional: true
  ROBOT_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: hcloud
        key: robot-password
        optional: true
  HCLOUD_LOAD_BALANCERS_LOCATION:
    value: hel1
```

Unfortunately, there is no documentation how it works or even there is no validation.

### Expected behavior

- provide a better documentation how to add arbitraty envs to the deployment
- add validation to values.yaml to disallow improper use.
